# https://github.com/kubernetes-incubator/kubespray/blob/master/docs/ansible.md

all:
  hosts:
    bastion:
      ansible_host: "{{ external_access }}"

  vars:
    # https://github.com/kubernetes-incubator/kubespray/blob/master/docs/vars.md
    # https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubespray-defaults/defaults/main.yaml
    ansible_user: centos
    # RBAC should be the default now
    #authorization_modes: [RBAC]
    #kube_version: v1.7.5
    helm_enabled: true
    helm_version: v2.6.2
    # Experimental (creates a local kubeconfig file):
    kubeconfig_localhost: true
    # kubespray bastion
    #ansible_ssh_common_args: "-F {{ playbook_dir }}/kubespray/ssh-bastion.conf"
    ansible_ssh_common_args: "-F kubespray/ssh-bastion.conf"
    # These are the external IPs of the master nodes
    #kube_additional_ip_sans:
    supplementary_addresses_in_ssl_keys:
    - "{{ external_access }}"

    # Docker
    #docker_version: '17.09'
    docker_version: stable
    #docker_rh_repo_base_url: 'https://download.docker.com/linux/centos/7/x86_64/stable'
    #docker_rh_repo_gpgkey: 'https://download.docker.com/linux/centos/gpg'
    # Copied from inventory/group_vars/k8s-cluster.yml + mtu
    docker_options: "--insecure-registry={{ kube_service_addresses }} --graph={{ docker_daemon_graph }} {{ docker_log_opts }} --mtu {{ ansible_default_ipv4.mtu }}"

    # Calico (default network plugin)
    # https://github.com/kubernetes-incubator/kubespray/blob/master/docs/calico.md
    #calico_mtu: "{{ ansible_default_ipv4.mtu | int }}"
    #calico_mtu: 1450
    #calico_endpoint_to_host_action: "ACCEPT"

    # Flannel (Calico doesn't seem to work)
    kube_network_plugin: flannel
    docker_enable_iptables: true

    external_access: 10.0.0.1

kube-master:
  children:
    kube-kubemaster-hosts:

kube-node:
  children:
    kube-kubeworker-hosts:

etcd:
  children:
    kube-kubemaster-hosts:

k8s-cluster:
  children:
    kube-node:
    kube-master:

idr-storage:
  hosts:
    kube-master-0:
